<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Data\RewardCatalog.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\RewardCatalog.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\CatQuest_Purribean\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>..\..\..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\CatQuest_Purribean\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="DOTween">
      <HintPath>..\..\..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\CatQuest_Purribean\Cat Quest III_Data\Managed\DOTween.dll</HintPath>
    </Reference>
    <Reference Include="Entitas">
      <HintPath>..\..\..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\CatQuest_Purribean\Cat Quest III_Data\Managed\Entitas.dll</HintPath>
    </Reference>
    <Reference Include="Gentlebros">
      <HintPath>..\..\..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\CatQuest_Purribean\Cat Quest III_Data\Managed\Gentlebros.dll</HintPath>
    </Reference>
    <Reference Include="PlayMaker">
      <HintPath>..\..\..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\CatQuest_Purribean\Cat Quest III_Data\Managed\PlayMaker.dll</HintPath>
    </Reference>
    <Reference Include="ProjectStar">
      <HintPath>..\..\..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\CatQuest_Purribean\Cat Quest III_Data\Managed\ProjectStar.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\CatQuest_Purribean\Cat Quest III_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\CatQuest_Purribean\Cat Quest III_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\CatQuest_Purribean\Cat Quest III_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
